import { c as createComponent, r as renderTemplate, a as renderComponent, m as maybeRenderHead } from './astro/server_CKYq2EXZ.mjs';
import 'kleur/colors';
import 'html-escaper';
import { $ as $$Layout } from './layout_DQkNcMVV.mjs';
/* empty css                               */

const $$Comentarios = createComponent(($$result, $$props, $$slots) => {
  return renderTemplate`${renderComponent($$result, "Layout", $$Layout, { "data-astro-cid-o4xbwcz7": true })} <title>Comentarios</title> ${maybeRenderHead()}<nav data-astro-cid-o4xbwcz7> <div class="mercado" data-astro-cid-o4xbwcz7>MERCADOS EL PORVENIR</div> <a href="https://yayumba.github.io/astro-mercado/" class="cerrarsecion" data-astro-cid-o4xbwcz7>cerrar secion</a> </nav> <section data-astro-cid-o4xbwcz7> <h2 data-astro-cid-o4xbwcz7>COMENTARIOS</h2> <div class="comentario" data-astro-cid-o4xbwcz7> <p data-astro-cid-o4xbwcz7>
Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem id vel quod error repellendus expedita beatae facere laborum. Repellat nihil, velit error fuga aperiam consequatur corporis incidunt saepe laudantium, tenetur reprehenderit, harum omnis dolorum quae ipsa cum nam? Voluptates sed nesciunt modi obcaecati ipsum repudiandae dolorum, voluptate beatae culpa nobis. ipsum dolor sit, amet consectetur adipisicing elit. Quod, rerum alias neque mollitia deleniti, dolore repellendus, minus quae officiis facilis exercitationem eos sed commodi nobis dicta illum ratione culpa eum?
</p> </div> <div class="correo" data-astro-cid-o4xbwcz7> <p data-astro-cid-o4xbwcz7>Lorem ipsum dolor sit amet, consectetur adipisicing.</p> </div> <div class="boton" data-astro-cid-o4xbwcz7> <input type="submit" value="ELIMINAR" data-astro-cid-o4xbwcz7> </div> </section> <section data-astro-cid-o4xbwcz7> <div class="comentario2" data-astro-cid-o4xbwcz7> <p data-astro-cid-o4xbwcz7>
Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem id vel quod error repellendus expedita beatae facere laborum. Repellat nihil, velit error fuga aperiam consequatur corporis incidunt saepe laudantium, tenetur reprehenderit, harum omnis dolorum quae ipsa cum nam? Voluptates sed nesciunt modi obcaecati ipsum repudiandae dolorum, voluptate beatae culpa nobis. ipsum dolor sit, amet consectetur adipisicing elit. Quod, rerum alias neque mollitia deleniti, dolore repellendus, minus quae officiis facilis exercitationem eos sed commodi nobis dicta illum ratione culpa eum?
</p> </div> <div class="correo2" data-astro-cid-o4xbwcz7> <p data-astro-cid-o4xbwcz7>Lorem ipsum dolor sit amet, consectetur adipisicing.</p> </div> <div class="boton2" data-astro-cid-o4xbwcz7> <input type="submit" value="ELIMINAR" data-astro-cid-o4xbwcz7> </div> </section> <section data-astro-cid-o4xbwcz7> <div class="comentario3" data-astro-cid-o4xbwcz7> <p data-astro-cid-o4xbwcz7>
Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem id vel quod error repellendus expedita beatae facere laborum. Repellat nihil, velit error fuga aperiam consequatur corporis incidunt saepe laudantium, tenetur reprehenderit, harum omnis dolorum quae ipsa cum nam? Voluptates sed nesciunt modi obcaecati ipsum repudiandae dolorum, voluptate beatae culpa nobis. ipsum dolor sit, amet consectetur adipisicing elit. Quod, rerum alias neque mollitia deleniti, dolore repellendus, minus quae officiis facilis exercitationem eos sed commodi nobis dicta illum ratione culpa eum?
</p> </div> <div class="correo3" data-astro-cid-o4xbwcz7> <p data-astro-cid-o4xbwcz7>Lorem ipsum dolor sit amet, consectetur adipisicing.</p> </div> <div class="boton3" data-astro-cid-o4xbwcz7> <input type="submit" value="ELIMINAR" data-astro-cid-o4xbwcz7> </div> </section> `;
}, "C:/Users/jerso/OneDrive/Escritorio/astro-mercado/src/pages/comentarios.astro", void 0);

const $$file = "C:/Users/jerso/OneDrive/Escritorio/astro-mercado/src/pages/comentarios.astro";
const $$url = "/astro-mercado/comentarios";

export { $$Comentarios as default, $$file as file, $$url as url };
